esphome:
  name: mud-kitchen-test

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: USB_CDC # This is to release a UART for the relays

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
#  - ssid: !secret bp_wifi_ssid
#    password: !secret bp_wifi_password

#mqtt:
#  broker: mqtt.valkenb.org
#  username: !secret mqtt_username
#  password: !secret mqtt_password

light:
  - platform: status_led
    name: "Mud Kitchen Test Status"
    pin: GPIO15
    
uart:

  - tx_pin: GPIO09
    id: uart1
    baud_rate: 115200

  - tx_pin: GPIO11
    id: uart2
    baud_rate: 115200

switch:

  - platform: template
    name: 'Mud Kitchen Test Conect Solar Panel'
    id: conect_solar_panel
    optimistic: true
    turn_on_action:
      - uart.write:
          id: uart1
          data: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write:
          id: uart1
          data: [0xA0, 0x01, 0x00, 0xA1]

  - platform: template
    name: 'Mud Kitchen Test Main Power'
    id: main_power
    optimistic: true
    turn_on_action:
      - uart.write:
          id: uart1
          data: [0xA0, 0x02, 0x01, 0xA3]
    turn_off_action:
      - uart.write:
          id: uart1
          data: [0xA0, 0x02, 0x00, 0xA2]

  - platform: template
    name: 'Mud Kitchen Test Pump'
    id: pump
    optimistic: true
    turn_on_action:
      - uart.write:
          id: uart2
          data: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write:
          id: uart2
          data: [0xA0, 0x01, 0x00, 0xA1]

  - platform: template
    name: 'Mud Kitchen Test Relay 4'
    optimistic: true
    turn_on_action:
      - uart.write:
          id: uart2
          data: [0xA0, 0x02, 0x01, 0xA3]
    turn_off_action:
      - uart.write:
          id: uart2
          data: [0xA0, 0x02, 0x00, 0xA2]

sensor:
  - platform: adc
    attenuation: 11db
    pin: GPIO3
    name: "Mud Kitchen Test Battery"
    update_interval: 5ms
    accuracy_decimals: 3
    filters:
      - multiply: 15
      - sliding_window_moving_average:
          window_size: 400
          send_every: 400
    on_value_range:
      - above: 10.0 # Provide power to pumps and lights above this.
        then:
          - switch.turn_on: main_power
      - below: 8.5 # Remove power to pumps and lights under this.
        then:
        - switch.turn_off: main_power
        - switch.turn_off: pump
      - above: 13.5 # Battery is overcharging, disconnecting charge source.
        then:
        - switch.turn_off: conect_solar_panel
          
  - platform: adc
    attenuation: 11db
    pin: GPIO5
    name: "Mud Kitchen Test Solar Panel"
    update_interval: 5ms
    accuracy_decimals: 3
    filters:
      - multiply: 15
      - sliding_window_moving_average:
          window_size: 400
          send_every: 400
    on_value_range:
      - above: 8 # Charge source has more than this, start charging.
        then:
          - switch.turn_on: conect_solar_panel
      - above: 14 # Charge source has too much power, disconnect. This may need adjusting if we disconnect while we still need power.
        then:
        - switch.turn_off: conect_solar_panel
      - below: 5 # Disconnect charger if we don't have charge power.
        then:
        - switch.turn_off: conect_solar_panel

          
  - platform: adc
    attenuation: 11db
    pin: GPIO7
    name: "Mud Kitchen Test Level Sensor"
    update_interval: 5ms
    accuracy_decimals: 3
    filters:
      - multiply: 15
      - sliding_window_moving_average:
          window_size: 400
          send_every: 400
    on_value_range:
      - above: 8 # Level sensor senses the top tank is low and the bottom one is high
        then:
          if:
            condition:
              switch.is_on: main_power
            then:
              script.execute: limited_time_pump
      - below: 5 # 
        then:
        - switch.turn_off: pump

script:
  - id: limited_time_pump
    mode: restart     # Pump will be kept on during time
                      # the latest time the script is executed
    then:
      - switch.turn_on: pump
      - delay: 2 hours
      - switch.turn_off: pump

